### ISSUE TITLE
你好，能帮助一下吗？TVM 这里困了好久了

### ISSUE THREAD

**Issue by zuowanbushiwo** [fantasyRqg/TVM_Android_rpc#3]
1. 我使用官网android rpc 编译编译出来的apk，总是有崩溃或者 只要remote.upload 后就会断连接。提了issue https://github.com/apache/tvm/issues/13290 目前还没人解释和指导。
2. 尝试使用你的工程，我使用如下dockerfile，编译docker 镜像

```
FROM python:3.8-bullseye

ENV DEBIAN_FRONTEND=noninteractive

# Install deps
RUN apt update && apt install -y --no-install-recommends git libgtest-dev cmake wget unzip libtinfo-dev libz-dev openjdk-11-jdk maven vim\
     libcurl4-openssl-dev g++ sudo python3-dev antlr4 && \
     pip install --upgrade pip && pip install pylint==1.9.4 six numpy pytest cython decorator scipy tornado \
     typed-ast pytest mypy orderedset antlr4-python3-runtime attrs requests "Pillow<7" "xgboost<1.6.0" cloudpickle packaging
	 
# LLVM
RUN echo deb http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-12 main \
     >> /etc/apt/sources.list.d/llvm.list && \
     wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - && \
     apt-get update && apt-get install -y llvm-12

RUN apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

ENV GRADLE_HOME /opt/gradle
ENV GRADLE_VERSION 7.5.1

RUN set -o errexit -o nounset \
    && echo "Downloading Gradle" \
    && wget --no-verbose --output-document=gradle.zip "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" \
    && echo "Installing Gradle" \
    && unzip gradle.zip \
    && rm gradle.zip \
    && mv "gradle-${GRADLE_VERSION}" "${GRADLE_HOME}/" \
    && ln --symbolic "${GRADLE_HOME}/bin/gradle" /usr/bin/gradle

ENV ANDROID_NDK_VERSION=21.3.6528147
ENV ANDROID_SDK_ROOT=/opt/android-sdk-root-linux
ENV ANDROID_HOME=$ANDROID_SDK_ROOT
ENV ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION
RUN curl -L https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -o /tmp/commandlinetools-linux.zip \
  && mkdir -p $ANDROID_SDK_ROOT \
  && cd $ANDROID_SDK_ROOT \
  && mkdir cmdline-tools \
  && cd cmdline-tools \
  && unzip /tmp/commandlinetools-linux.zip \
  && mv cmdline-tools latest \
  && yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses \
  && $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-26" "platforms;android-27" "ndk;${ANDROID_NDK_VERSION}" "build-tools;26.0.3" "build-tools;27.0.3" "tools"

RUN bash $ANDROID_NDK_HOME/build/tools/make-standalone-toolchain.sh --platform=android-24 --use-llvm --arch=arm64 --install-dir=/opt/android-toolchain-arm64	 
ENV PYTHONPATH=/usr/tvm/python:/usr/tvm/topi/python:${PYTHONPATH}
ENV PATH "${PATH}:${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin"
ENV PATH "${PATH}:${ANDROID_NDK_HOME}"
ENV TVM_NDK_CC=/opt/android-toolchain-arm64/bin/aarch64-linux-android-g++
```
3. 然后 切换到指定的 tvm commit id   59c0ef80b5186e1840523f6a8b60071f78436212
4.  然后编译 tvm: 
```
       cmake -DUSE_LLVM=llvm-config-12 \
      -DUSE_RPC=ON \
      -DUSE_SORT=ON \
      -DUSE_GRAPH_EXECUTOR=ON \
      ..
```
6. clone 你的TVM_Android_rpc项目，并对做一些修改
```
diff --git a/app/build.gradle b/app/build.gradle
index 8a77733..cacbbb4 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -7,7 +7,7 @@ plugins {

 android {
     compileSdkVersion 29
-    ndkVersion "23.0.7530507"
+    ndkVersion "21.3.6528147"
     defaultConfig {
         applicationId "com.rqg.tvm_rpc"
         minSdkVersion 21
@@ -32,7 +32,7 @@ android {
     externalNativeBuild {
         cmake {
             path "src/main/cpp/CMakeLists.txt"
-            version "3.21.3"
+            version "3.18.4"
         }
     }

diff --git a/app/src/main/cpp/CMakeLists.txt b/app/src/main/cpp/CMakeLists.txt
index f8b3bc8..2b79629 100644

...skipping 1 line
+++ b/app/src/main/cpp/CMakeLists.txt
@@ -1,10 +1,10 @@
-cmake_minimum_required(VERSION 3.19)
+cmake_minimum_required(VERSION 3.18)

 project(tvm_glue)

 set(CMAKE_CXX_STANDARD 17)

-set(TVM_ROOT /Users/rqg/Playground/tvm)
+set(TVM_ROOT /usr/tvm)
 include_directories(${TVM_ROOT})
 include_directories(${TVM_ROOT}/include)
 include_directories(${TVM_ROOT}/3rdparty/dlpack/include)

```
7. 在容器中 运行  python3 -m tvm.exec.query_rpc_tracker --host=0.0.0.0 --port=9190

8.  编译 TVM_Android_rpc 工程 ，然后安装 apk，使用如下参数连接：
![image](https://user-images.githubusercontent.com/3354428/201027862-5ff45859-d49d-4ac8-85a2-d2a88dfdeeac.png)
9.  docker 容器中运行: python3 -m tvm.exec.query_rpc_tracker --host=0.0.0.0 --port=9190
```
Tracker address 0.0.0.0:9190

Server List
------------------------------
server-address           key
------------------------------
  192.168.30.233:9090    server:andriod
------------------------------

Queue Status
-------------------------------
key       total  free  pending
-------------------------------
andriod   1      1     0
-------------------------------
```

10, 对 android_acl.py 对如下更改：
-device_key = 'acl'
-tracker_ip = '192.168.31.79'
-tracker_port = 9190
-toolchain = '/Users/rqg/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang'
+device_key = 'android'
+tracker_ip = '192.168.30.233'
+tracker_port = 9090
+toolchain = '/opt/android-sdk-root-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++'

11.  运行 android_acl.py 报如下错误:

```
root@tvm:/# /usr/local/bin/python /usr/TVM_Android_rpc/android_acl.py
Traceback (most recent call last):
  File "/usr/TVM_Android_rpc/android_acl.py", line 29, in <module>
    lib = relay.build(module, target=target)
  File "/usr/tvm/python/tvm/relay/build_module.py", line 364, in build
    graph_json, runtime_mod, params = bld_mod.build(
  File "/usr/tvm/python/tvm/relay/build_module.py", line 161, in build
    self._build(
  File "/usr/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  15: TVMFuncCall
  14: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::relay::backend::RelayBuildModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#3}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  13: tvm::relay::backend::RelayBuildModule::BuildRelay(tvm::IRModule, tvm::runtime::String const&)
  12: tvm::relay::backend::ExecutorCodegen::Codegen(tvm::IRModule, tvm::relay::Function const&, tvm::runtime::String)
  11: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::relay::backend::GraphExecutorCodegenModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  10: tvm::relay::backend::GraphExecutorCodegen::Codegen(tvm::IRModule, tvm::relay::Function, tvm::runtime::String)
  9: tvm::transform::Pass::operator()(tvm::IRModule) const
  8: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  7: tvm::transform::SequentialNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  6: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  5: tvm::transform::ModulePassNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  4: _ZN3tvm7runtime13PackedFun
  3: tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::IRModule, tvm::transform::PassContext)>::AssignTypedLambda<tvm::relay::tec::LowerTE(tvm::runtime::String, tvm::CompilationConfig, std::function<void (tvm::BaseFunc)>)::{lambda(tvm::IRModule, tvm::transform::PassContext)#1}>(tvm::relay::tec::LowerTE(tvm::runtime::String, tvm::CompilationConfig, std::function<void (tvm::BaseFunc)>)::{lambda(tvm::IRModule, tvm::transform::PassContext)#1})::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs const, tvm::runtime::TVMRetValue) const
  2: tvm::relay::tec::LowerTE(tvm::IRModule const&, tvm::runtime::String const&, std::function<void (tvm::BaseFunc)>, tvm::CompilationConfig)
  1: tvm::relay::tec::TECompilerImpl::LowerExternalFunctions()
  0: _ZN3tvm7runtime6deta
  File "/usr/tvm/src/relay/backend/te_compiler.cc", line 281
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (pf) is false: Failed to find the external codegen tool for relay.ext.arm_compute_lib
```

**Comment by fantasyRqg** [comment]
`Failed to find the external codegen tool for relay.ext.arm_compute_lib`  这是 host 端无法使用 ACL 生成执行代码

编译 host 时 配置 [set(USE_ARM_COMPUTE_LIB OFF)](https://github.com/apache/tvm/blob/302cee99482a9afae3b4a2b0b396083d66b70577/cmake/config.cmake#L248) 为 ON

之前一直没看消息，今天看了下。但愿你还没放弃

**Comment by zuowanbushiwo** [comment]
没放弃，谢谢！
